In [1]:
import pandas as pd

In [2]:
df=pd.read_table(r'https://raw.githubusercontent.com/bapujik/dataSets/main/SMSSpamCollection',sep="\t",header=None,names=["label","sms_message"])

In [3]:
df

label                                        sms_message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df.label.unique()

array(['ham', 'spam'], dtype=object)

In [5]:
#df.sms_message.unique()

In [6]:
df.head()

label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df["label"]=df.label.map({"ham":0,"spam":1})

In [8]:
df.head()

label                                        sms_message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.sms_message

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: sms_message, Length: 5572, dtype: object

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
count_vector=CountVectorizer()

In [12]:
type(count_vector)

sklearn.feature_extraction.text.CountVectorizer

In [13]:
count_vector

CountVectorizer()

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(df["sms_message"],df["label"],random_state=1)

In [16]:
X_train.shape

(4179,)

In [17]:
X_test.shape

(1393,)

In [18]:
df["sms_message"].shape

(5572,)

In [19]:
X_train[780]

'That means get the door'

In [20]:
train=count_vector.fit_transform(X_train)

In [21]:
test=count_vector.transform(X_test)

In [22]:
train

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [23]:
train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
#count_vector.get_feature_names()

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
naive_bayes=MultinomialNB()

In [28]:
model=naive_bayes.fit(train,y_train)

### Pickling Machine Learning Model (saving Model)

In [29]:
import pickle
filename="F:\Online_ML_Course\spamsms"
outfile=open(filename,"wb")
pickle.dump(model,outfile)
outfile.close()

### Pickling Vectorizer (saving vectorizer)

In [30]:
fname=r"F:\Online_ML_Course\vectorizer"
outfile=open(fname,"wb")
pickle.dump(count_vector,outfile)
outfile.close()

In [31]:
predictions=naive_bayes.predict(test)

In [32]:
predictions

array([0, 0, 0, ..., 0, 1, 0])

In [33]:
predlist=list(zip(predictions,y_test))

In [34]:
#predlist

In [35]:
#Evaluating the model

In [36]:
from sklearn.metrics import accuracy_score,precision_score

In [37]:
score=accuracy_score(y_test,predictions)

In [38]:
score

0.9885139985642498

In [39]:
##real example

In [40]:
X_test

1078                         Yep, by the pretty sculpture
4028        Yes, princess. Are you going to make me moan?
958                            Welp apparently he retired
4642                                              Havent.
4674    I forgot 2 ask ü all smth.. There's a card on ...
                              ...                        
3207                                        At home also.
4655                     Hope you are having a great day.
1140    Message:some text missing* Sender:Name Missing...
1793    WIN: We have a winner! Mr. T. Foley won an iPo...
1710    U meet other fren dun wan meet me ah... Muz b ...
Name: sms_message, Length: 1393, dtype: object

In [41]:
X_test[1793]

'WIN: We have a winner! Mr. T. Foley won an iPod! More exciting prizes soon, so keep an eye on ur mobile or visit www.win-82050.co.uk'

In [42]:
#predictions=naive_bayes.predict(test[1793])

In [44]:
sms1=input("Enter sms message Recieved")
predict_sms=naive_bayes.predict(count_vector.transform([sms1]))
print(predict_sms[0])
if(predict_sms[0]==0):
    print("Message is ham")
else:
    print("message is spam")

Enter sms message RecievedCLick Here
0
Message is ham
